ALTER TABLE freebies
  ADD COLUMN IF NOT EXISTS image_url TEXT NULL AFTER link;

ALTER TABLE gear
  ADD COLUMN IF NOT EXISTS image_url TEXT NULL AFTER link;

ALTER TABLE testimonials
  ADD COLUMN IF NOT EXISTS image_url TEXT NULL AFTER rating;

ALTER TABLE contact_messages
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE admin_users
  ADD COLUMN IF NOT EXISTS session_version INT UNSIGNED NOT NULL DEFAULT 1 AFTER role;
